# Home Assistant Barcode Scanner - Configuration Example

# MQTT broker configuration
mqtt:
  # MQTT broker URL with protocol (required)
  # Supported protocols: mqtt://, mqtts://, ws://, wss://
  # Examples:
  #   mqtt://homeassistant.local:1883    (standard MQTT)
  #   mqtts://homeassistant.local:8883   (MQTT over SSL/TLS)
  #   ws://homeassistant.local:1883      (MQTT over WebSocket)
  #   wss://homeassistant.local:8883     (MQTT over Secure WebSocket)
  broker_url: "mqtt://homeassistant.local:1883"

  # MQTT client ID
  client_id: "ha-barcode-bridge"

  # MQTT authentication (optional)
  username: "mqtt_user"
  password: "mqtt_password"

  # MQTT QoS level: 0, 1, or 2
  qos: 1

  # Keep alive interval in seconds
  keep_alive: 60

  # Skip TLS certificate verification for mqtts:// and wss:// connections
  # WARNING: Only use this for testing with self-signed certificates
  insecure_skip_verify: false

# Configure multiple barcode scanners
scanners:
  # Scanner identified by USB VID/PID only (single device scenario)
  warehouse_scanner:
    name: "Warehouse Scanner" # Optional friendly name
    identification:
      vendor_id: 0x60e # USB Vendor ID (required)
      product_id: 0x16c7 # USB Product ID (required)
      # serial: auto-detected from device when only one matching VID/PID found
    keyboard_layout: "us" # Keyboard layout: "us", "es", etc. (defaults to "us")
    termination_char: "enter" # "enter", "tab", or "none" for auto-timeout
  # Scanner with serial for multiple identical devices
  checkout_scanner_1:
    name: "Checkout #1"
    identification:
      vendor_id: 0x60e
      product_id: 0x16c7
      serial: "ABC123" # Specify when multiple devices have same VID/PID
    keyboard_layout: "us" # Optional keyboard layout
    termination_char: "enter" # "enter", "tab", or "none" for auto-timeout

  # Second scanner with unique ID
  checkout_scanner_2:
    name: "Checkout #2"
    identification:
      vendor_id: 0x60e
      product_id: 0x16c7
      # Note: Each scanner needs a unique configured ID (checkout_scanner_2)
      # MQTT topics are generated from this ID, not from hardware serials
    keyboard_layout: "es" # Spanish keyboard layout example
    termination_char: "enter" # "enter", "tab", or "none" for auto-timeout

# Home Assistant integration configuration
homeassistant:
  # MQTT discovery prefix
  discovery_prefix: "homeassistant"

  # Unique instance identifier (optional - uses hostname if not specified)
  # Use this when running multiple instances of this application
  instance_id: "workstation"

# Logging configuration
logging:
  # Log level: debug, info, warn, error
  level: "info"

  # Log format: text, json
  format: "text"
