site_name: Go Project Template
site_url: https://miguelangel-nubla.github.io/homeassistant-barcode-scanner
repo_name: miguelangel-nubla/homeassistant-barcode-scanner
repo_url: https://github.com/miguelangel-nubla/homeassistant-barcode-scanner
edit_uri: ""

site_dir: public

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.sections

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
